### ISSUE TITLE
Enhance usage config to include score bounds/type

### ISSUE THREAD

**Issue by gbowlin** [epic-open-source/seismometer#51]
## Is your feature request related to a problem? Please describe

When describing model outcomes, we expect a threshold to come from the user, but its not always clear what type of outcome we have (0-100 or 0.00 to 1.00 for percentiles versus probabilities)

## Describe the solution you'd like

For clarity, output configuration should be more than just a column name, but should include expected valid values that Seismometer can filter based on, or provide as limits. Similar to how we use a custom class for the `cohort` columns. 

For example:

```
primary_output: Primary Model Score
outputs:
  - source: ScoreName1
    display_name: Primary Model Score
    type: numeric
    lower_bound: 0
    upper_bound: 1
  - source: ScoreName2
    display_name: A Second Score
    type: numeric
    lower_bound: 0
    upper_bound: 100
  - source: ScoreName3
    display_name: A Third Score for completeness
    type: numeric
    lower_bound: -12
    upper_bound: 144
```

Where `type` could potentially be extended to allow categorical scores in the future.
